TWITTER_KEY: 'xCnzm3NQmeN8kN8PK5j4Q'
TWITTER_SECRET: 'KKZAfHy9L22QuIbm0v9G03KhsotFzKqzT12nIjcXJaI'
OAUTH_TOKEN: '1414963501-FtI99ayJANcmVJX5HOuHD8NECLw2LLuSZ83yjBY'
OAUTH_TOKEN_SECRET: 'f1Wdzlrf6uWCXy1Ou7QawTQjbf1JaNcGhSm8eBc1JM'