TWITTER_KEY: 'yWoHtxlmeHzmeSYv7WRDw'
TWITTER_SECRET: 'edDIiT72LU07kmGttUXejmLFHYpc42jD7pc3VOOSqU'
OAUTH_TOKEN: '1414963501-il3rE2K0iwciWkiqwRxwL8sy5bGmlphMSB3IQ1B'
OAUTH_TOKEN_SECRET: 'q3tK0leOUYY1i0sGUxLC0NyzUw0lPeh9vWJ6TfUaw'